const initialData = [
  {
    key: 0,
    type: "Banner",
    armedia1_value: "v2.com/1",
    armedia1_edit: false,
    armedia1_valid: "url",
    armedia2_value: "v2.com/12",
    armedia2_valid: "url",
    armedia2_edit: true,
    twodtarget_value: "v2.com/12",
    twodtarget_valid: "url",
    twodtarget_edit: true,
    turnleft_value: "v2.com/12",
    turnleft_valid: "url",
    turnleft_edit: false,
    turnright_value: "v2.com/12",
    turnright_valid: "url",
    turnright_edit: true,
    latitude_value: 45,
    latitude_valid: "url",
    latitude_edit: true,
    longitude_value: 100,
    longitude_valid: "url",
    longitude_edit: true,
  },
  {
    key: 1,
    type: "Un Boxing",
    armedia1_value: "v2.com/1",
    armedia1_edit: true,
    armedia1_valid: "url",
    armedia2_value: "v2.com/12",
    armedia2_valid: "url",
    armedia2_edit: false,
    twodtarget_value: "v2.com/22",
    twodtarget_valid: "url",
    twodtarget_edit: false,
    turnleft_value: "v2.com/24",
    turnleft_valid: "url",
    turnleft_edit: true,
    turnright_value: "v2.com/25",
    turnright_valid: "url",
    turnright_edit: true,
    latitude_value: "55",
    latitude_valid: "url",
    latitude_edit: true,
    longitude_value: "110",
    longitude_valid: "url",
    longitude_edit: true,
  },
  {
    key: 2,
    type: "Banner",
    armedia1_value: "v2.com/1",
    armedia1_edit: true,
    armedia1_valid: "url",
    armedia2_value: "v2.com/14",
    armedia2_valid: "url",
    armedia2_edit: true,
    twodtarget_value: "v2.com/42",
    twodtarget_valid: "url",
    twodtarget_edit: true,
    turnleft_value: "v2.com/12",
    turnleft_valid: "url",
    turnleft_edit: true,
    turnright_value: "v2.com/72",
    turnright_valid: "url",
    turnright_edit: true,
    latitude_value: "65",
    latitude_valid: "url",
    latitude_edit: true,
    longitude_value: "120",
    longitude_valid: "url",
    longitude_edit: true,
  },
  {
    key: 3,
    type: "Banner",
    armedia1_value: "v2.com/1",
    armedia1_edit: true,
    armedia1_valid: "url",
    armedia2_value: "v2.com/12",
    armedia2_valid: "url",
    armedia2_edit: true,
    twodtarget_value: "v2.com/12",
    twodtarget_valid: "url",
    twodtarget_edit: true,
    turnleft_value: "v2.com/12",
    turnleft_valid: "url",
    turnleft_edit: true,
    turnright_value: "v2.com/12",
    turnright_valid: "url",
    turnright_edit: true,
    latitude_value: "67",
    latitude_valid: "url",
    latitude_edit: true,
    longitude_value: "110",
    longitude_valid: "url",
    longitude_edit: true,
  },
  {
    key: 4,
    type: "No Banner",
    armedia1_value: "v2.com/1",
    armedia1_edit: true,
    armedia1_valid: "url",
    armedia2_value: "v2.com/12",
    armedia2_valid: "url",
    armedia2_edit: true,
    twodtarget_value: "v2.com/12",
    twodtarget_valid: "url",
    twodtarget_edit: true,
    turnleft_value: "v2.com/12",
    turnleft_valid: "url",
    turnleft_edit: true,
    turnright_value: "v2.com/12",
    turnright_valid: "url",
    turnright_edit: true,
    latitude_value: "67",
    latitude_valid: "url",
    latitude_edit: true,
    longitude_value: "135",
    longitude_valid: "url",
    longitude_edit: true,
  },
];
export default initialData;
