const originData = [
  {
    key: 0,
    type: "Banner",
    armedia1: "v2.com/1",
    armedia2: "v2.com/12",
    twodtarget: "v2.com/13",
    turnleft: "v2.com/14",
    turnright: "v2.com/15",
    latitude: "45",
    longitude: "110",
    mascot: "<null>",
  },
  {
    key: 1,
    type: "Banner",
    armedia1: "v2.com/2",
    armedia2: "v2.com/22",
    twodtarget: "v2.com/23",
    turnleft: "v2.com/24",
    turnright: "v2.com/25",
    latitude: "45",
    longitude: "110",
    mascot: "<null>",
  },
  {
    key: 2,
    type: "Banner",
    armedia1: "v2.com/3",
    armedia2: "v2.com/32",
    twodtarget: "v2.com/33",
    turnleft: "v2.com/34",
    turnright: "v2.com/35",
    latitude: "45",
    longitude: "110",
    mascot: "<null>",
  },
  {
    key: 3,
    type: "Un Boxing",
    armedia1: "v2.com/4",
    armedia2: "v2.com/42",
    twodtarget: "v2.com/43",
    turnleft: "v2.com/44",
    turnright: "v2.com/45",
    latitude: "45",
    longitude: "110",
    mascot: "<null>",
  },
  {
    key: 4,
    type: "No Banner",
    armedia1: "v2.com/5",
    armedia2: "v2.com/52",
    twodtarget: "v2.com/53",
    turnleft: "v2.com/54",
    turnright: "v2.com/55",
    latitude: "45",
    longitude: "110",
    mascot: "yes",
  },
];
export default originData;
