 const initialData = [
  {
    key: 0,
    type: "Banner",
    armedia1: { value: "v2.com/1", edit: false, validationType: "url" },
    armedia2: { value: "v2.com/12", edit: true, validationType: "url" },
    twodtarget: { value: "v2.com/13", edit: true, validationType: "url" },
    turnleft: { value: "v2.com/14", edit: false, validationType: "url" },
    turnright: { value: "v2.com/15", edit: true, validationType: "url" },
    latitude: { value: "45", edit: true, validationType: "latitude" },
    longitude: { value: "100", edit: true, validationType: "longitude" },
  },
  {
    key: 1,
    type: "Un Boxing",
    armedia1: { value: "v2.com/2", edit: true, validationType: "url" },
    armedia2: { value: "v2.com/22", edit: false, validationType: "url" },
    twodtarget: { value: "v2.com/23", edit: false, validationType: "url" },
    turnleft: { value: "v2.com/24", edit: true, validationType: "url" },
    turnright: { value: "v2.com/25", edit: true, validationType: "url" },
    latitude: { value: "55", edit: true, validationType: "latitude" },
    longitude: { value: "110", edit: true, validationType: "longitude" },
  },
  {
    key: 2,
    type: "Banner",
    armedia1: { value: "v2.com/3", edit: true, validationType: "url" },
    armedia2: { value: "v2.com/32", edit: true, validationType: "url" },
    twodtarget: { value: "v2.com/33", edit: true, validationType: "url" },
    turnleft: { value: "v2.com/34", edit: true, validationType: "url" },
    turnright: { value: "v2.com/35", edit: true, validationType: "url" },
    latitude: { value: "65", edit: true, validationType: "latitude" },
    longitude: { value: "120", edit: true, validationType: "longitude" },
  },
  {
    key: 3,
    type: "Banner",
    armedia1: { value: "v2.com/4", edit: true, validationType: "url" },
    armedia2: { value: "v2.com/42", edit: true, validationType: "url" },
    twodtarget: { value: "v2.com/43", edit: true, validationType: "url" },
    turnleft: { value: "v2.com/44", edit: true, validationType: "url" },
    turnright: { value: "v2.com/35", edit: true, validationType: "url" },
    latitude: { value: "75", edit: true, validationType: "latitude" },
    longitude: { value: "130", edit: true, validationType: "longitude" },
  },
  {
    key: 4,
    type: "No Banner",
    armedia1: { value: "v2.com/5", edit: true, validationType: "url" },
    armedia2: { value: "v2.com/52", edit: true, validationType: "url" },
    twodtarget: { value: "v2.com/53", edit: true, validationType: "url" },
    turnleft: { value: "v2.com/54", edit: true, validationType: "url" },
    turnright: { value: "v2.com/55", edit: true, validationType: "url" },
    latitude: { value: "85", edit: true, validationType: "latitude" },
    longitude: { value: "140", edit: true, validationType: "longitude" },
  },
];
export default initialData