const initialData = [
  {
    key: 0,
    type: "Banner",
    armedia1_value: "v2.com/1",
    armedia1_edit: true,
    armedia1_valid: "url",
    armedia2_value: "v2.com/12",
    armedia2_valid: "url",
    armedia2_edit: true,
    twodtarget_value: "v2.com/12",
    twodtarget_valid: "url",
    twodtarget_edit: true,
    turnleft_value: "v2.com/12",
    turnleft_valid: "url",
    turnleft_edit: true,
    turnright_value: "v2.com/12",
    turnright_valid: "url",
    turnright_edit: true,
    latitude_value: 140,
    latitude_valid: "url",
    latitude_edit: true,
    longitude_value: 85,
    longitude_valid: "url",
    longitude_edit: true,
  },
  {
    key: 1,
    type: "Un Boxing",
    armedia1_value: "v2.com/1",
    armedia1_edit: false,
    armedia1_valid: "url",
    armedia2_value: "v2.com/12",
    armedia2_valid: "url",
    armedia2_edit: true,
    twodtarget_value: "v2.com/12",
    twodtarget_valid: "url",
    twodtarget_edit: true,
    turnleft_value: "v2.com/12",
    turnleft_valid: "url",
    turnleft_edit: false,
    turnright_value: "v2.com/12",
    turnright_valid: "url",
    turnright_edit: true,
    latitude_value: "v2.com/12",
    latitude_valid: "url",
    latitude_edit: false,
    longitude_value: "v2.com/12",
    longitude_valid: "url",
    longitude_edit: false,
  },
  {
    key: 2,
    type: "Banner",
    armedia1_value: "v2.com/1",
    armedia1_edit: false,
    armedia1_valid: "url",
    armedia2_value: "v2.com/12",
    armedia2_valid: "url",
    armedia2_edit: true,
    twodtarget_value: "v2.com/12",
    twodtarget_valid: "url",
    twodtarget_edit: true,
    turnleft_value: "v2.com/12",
    turnleft_valid: "url",
    turnleft_edit: false,
    turnright_value: "v2.com/12",
    turnright_valid: "url",
    turnright_edit: true,
    latitude_value: "v2.com/12",
    latitude_valid: "url",
    latitude_edit: false,
    longitude_value: "v2.com/12",
    longitude_valid: "url",
    longitude_edit: false,
  },
  {
    key: 3,
    type: "Banner",
    armedia1_value: "v2.com/1",
    armedia1_edit: false,
    armedia1_valid: "url",
    armedia2_value: "v2.com/12",
    armedia2_valid: "url",
    armedia2_edit: true,
    twodtarget_value: "v2.com/12",
    twodtarget_valid: "url",
    twodtarget_edit: true,
    turnleft_value: "v2.com/12",
    turnleft_valid: "url",
    turnleft_edit: false,
    turnright_value: "v2.com/12",
    turnright_valid: "url",
    turnright_edit: true,
    latitude_value: "v2.com/12",
    latitude_valid: "url",
    latitude_edit: false,
    longitude_value: "v2.com/12",
    longitude_valid: "url",
    longitude_edit: true,
  },
  {
    key: 4,
    type: "No Banner",
    armedia1_value: "v2.com/1",
    armedia1_edit: false,
    armedia1_valid: "url",
    armedia2_value: "v2.com/12",
    armedia2_valid: "url",
    armedia2_edit: true,
    twodtarget_value: "v2.com/12",
    twodtarget_valid: "url",
    twodtarget_edit: true,
    turnleft_value: "v2.com/12",
    turnleft_valid: "url",
    turnleft_edit: true,
    turnright_value: "v2.com/12",
    turnright_valid: "url",
    turnright_edit: true,
    latitude_value: "v2.com/12",
    latitude_valid: "url",
    latitude_edit: false,
    longitude_value: "v2.com/12",
    longitude_valid: "url",
    longitude_edit: false,
  },
];
export default initialData;
